# Em Python, é possível encadear exceções utilizando a palavra-chave 'from'

